### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by lebarsfa** [codac-team/codac#21]
**2021 UPDATE : Tubex has been renamed to Codac, here is the updated sample : https://www.ensta-bretagne.fr/lebars/Share/codac_test_win.zip.**

If you just want to quickly test Tubex in C++ on Windows, try https://www.ensta-bretagne.fr/lebars/Share/tubex_test_win.zip.

Otherwise, if you need to rebuild the library (e.g. to get latest updates or modify it), try this :
- Download http://download.qt.io/archive/qt/5.12/5.12.6/qt-opensource-windows-x86-5.12.6.exe
- If needed disconnect from the Internet if you do not want the Qt installer to ask for registration
- Run `qt-opensource-windowsx86-5.12.6.exe` and select `Qt\Qt 5.12.6\MinGW 7.3.0 32 bit` and `Qt\Developer and Designer Tools\MinGW 7.3.0 32 bit` options (in addition to existing selected options)
- Connect to the Internet if you disconnected it previously
- Install Chocolatey package manager by opening PowerShell as admin (right-click on Windows Start button) and run 
``` PowerShell
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
```
- Then, install Ibex and Tubex prerequisites 
``` PowerShell
choco install -y cmake git wget winflexbison make patch --installargs 'ADD_CMAKE_TO_PATH=System'
refreshenv
wget https://github.com/ros2/choco-packages/releases/download/2020-02-24/eigen.3.3.4.nupkg --no-check-certificate -nv
choco install -y eigen.3.3.4.nupkg
```
- Launch `Git Bash` app and inside, run
``` bash
export PATH=/c/Qt/Qt5.12.6/Tools/mingw730_32/bin:$PATH
cd Downloads
git clone https://github.com/ibex-team/ibex-lib.git
cd ibex-lib
mkdir build ; cd build
cmake -G "MSYS Makefiles" -D CMAKE_INSTALL_PREFIX="../../ibex" -D CMAKE_CXX_FLAGS="-fPIC" -D CMAKE_C_FLAGS="-fPIC" ..
cmake --build . --target install
cd ../..    

git clone https://github.com/SimonRohou/tubex-lib
cd tubex-lib 
git submodule init ; git submodule update
mkdir build ; cd build
cmake -G "MSYS Makefiles" -D CMAKE_BUILD_TYPE=Release -D CMAKE_PREFIX_PATH="../ibex" -D CMAKE_INSTALL_PREFIX="../../tubex" ..
cmake --build . --target install
cd ../
```
- Then replace `ibex` and `tubex` folders in www.ensta-bretagne.fr/lebars/Share/tubex_test_win.zip with the new ones…

**Comment by SimonRohou** [comment]
Hi Fabrice, thanks for this help!

I updated the manual of Tubex to point to this GitHub issue:
http://simon-rohou.fr/research/tubex-lib/doc/install/01-installation.html

**Comment by lebarsfa** [comment]
Closing since there were updates clarifying the installation in different situations.
