### ISSUE TITLE
CN issue in v0.1.5?

### ISSUE THREAD

**Issue by lebarsfa** [codac-team/codac#47]
There might be an issue in v0.1.5 where as soon as we try to use e.g. `ctc::deriv`, we get an abort error at https://github.com/codac-team/codac/blob/7fdbc3fe10fa981f91bbc476ff239464aedeb678/src/core/contractors/dyn/codac_CtcLinobs.cpp#L43-L46 possibly due to https://github.com/codac-team/codac/blob/7fdbc3fe10fa981f91bbc476ff239464aedeb678/src/core/contractors/codac_predef_contractors.cpp#L15-L22 which triggers a construction of `CtcChain()`.
This might be related to the tests that are failing : https://github.com/codac-team/codac/runs/3371253298?check_suite_focus=true#step:4:7754

**Comment by SimonRohou** [comment]
Fixed in 5cf92232da71aa4bf8e329ac2ceb99bd46969dcf.
